<?php

/**
 * This file is part of the Cubiche/Serializer component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Serializer\Tests\Units\Exception;

use Cubiche\Core\Serializer\Exception\SerializationException;
use Cubiche\Core\Serializer\Tests\Units\TestCase;

/**
 * SerializationException class.
 *
 * Generated by TestGenerator on 2016-04-29 at 17:37:57.
 */
class SerializationExceptionTests extends TestCase
{
    /**
     * Test class.
     */
    public function testClass()
    {
        $this
            ->testedClass
                ->extends(\RuntimeException::class)
        ;
    }

    /*
     * Test invalidObject method.
     */
    public function testInvalidObject()
    {
        $this
            ->given($cause = new \Exception('some cause'))
            ->when($exception = SerializationException::invalidObject('foo', $cause))
            ->then()
                ->object($exception)
                    ->isInstanceOf(SerializationException::class)
                ->integer($exception->getCode())
                    ->isEqualTo(0)
                ->object($exception->getPrevious())
                    ->isIdenticalTo($cause)
        ;

        $this
            ->given($exception = SerializationException::invalidObject('bar'))
            ->then()
                ->variable($exception->getPrevious())
                    ->isNull()
        ;
    }

    /*
     * Test invalidClass method.
     */
    public function testInvalidClass()
    {
        $this
            ->given($cause = new \Exception('some cause'))
            ->when($exception = SerializationException::invalidClass('foo', $cause))
            ->then()
                ->object($exception)
                    ->isInstanceOf(SerializationException::class)
                ->integer($exception->getCode())
                    ->isEqualTo(0)
                ->object($exception->getPrevious())
                    ->isIdenticalTo($cause)
        ;

        $this
            ->given($exception = SerializationException::invalidClass('bar'))
            ->then()
                ->variable($exception->getPrevious())
                    ->isNull()
        ;
    }

    /*
     * Test propertyNotFound method.
     */
    public function testPropertyNotFound()
    {
        $this
            ->given($cause = new \Exception('some cause'))
            ->when($exception = SerializationException::propertyNotFound('foo', TestCase::class, $cause))
            ->then()
                ->object($exception)
                    ->isInstanceOf(SerializationException::class)
                ->integer($exception->getCode())
                    ->isEqualTo(0)
                ->object($exception->getPrevious())
                    ->isIdenticalTo($cause)
        ;

        $this
            ->given($exception = SerializationException::propertyNotFound('bar', TestCase::class))
            ->then()
                ->variable($exception->getPrevious())
                    ->isNull()
        ;
    }

    /*
     * Test invalidMapping method.
     */
    public function testInvalidMapping()
    {
        $this
            ->given($cause = new \Exception('some cause'))
            ->when($exception = SerializationException::invalidMapping('foo', $cause))
            ->then()
                ->object($exception)
                    ->isInstanceOf(SerializationException::class)
                ->integer($exception->getCode())
                    ->isEqualTo(0)
                ->object($exception->getPrevious())
                    ->isIdenticalTo($cause)
        ;
    }
}
